pipeline {
    agent any 

    stages {
        stage('Build HelloWorld 1') {
            agent any 
            steps {
                echo 'Building HelloWorld1'
            }
        }
        stage('Test HelloWorld1') {
            agent any
            steps {
                echo 'Testing HelloWorld1 ...'
            }
        }
    }
}