pipeline {
    agent any 

    stages {
        stage('Echo HelloWorld 1') {
            agent any 
            steps {
                echo 'Echo HelloWorld1'
            }
        }
        stage('Test HelloWorld1') {
            agent any
            steps {
                powershell '''
                'javac HelloWorld.java '
                'java HelloWorld'
                '''
            }
        }
    }
}